export const SPECIALTIES = [
  'General Medicine',
  'Cardiology',
  'Dermatology',
  'Endocrinology',
  'ENT (Otolaryngology)',
  'Gastroenterology',
  'General Surgery',
  'Gynecology',
  'Nephrology',
  'Neurology',
  'Oncology',
  'Ophthalmology',
  'Orthopedics',
  'Pediatrics',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Rheumatology',
  'Urology',
  'Anesthesiology',
  'Dentistry',
  'Pathology',
  'Emergency Medicine',
  'Family Medicine',
  'Physiotherapy',
] as const;

export type Specialty = (typeof SPECIALTIES)[number];
